export function TermsPage() {
  return (
    <div className="container max-w-2xl space-y-6 py-8 text-foreground/90">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Use</h1>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Not legal advice</h2>
        <p>
          This service is a research aid. Answers are generated by a large
          language model from a curated set of Indian statutes and judgments.
          The output is not legal advice, does not establish an
          attorney-client relationship, and must not be relied upon for any
          real legal decision.
        </p>
        <p>
          If you have a real legal question — especially anything involving
          potential criminal liability, ongoing investigation, or court
          proceedings — consult a qualified advocate licensed in your
          jurisdiction.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Scope</h2>
        <p>
          The corpus covers <strong>robbery offences</strong> under Indian
          criminal law: BNS §§309-311 (Bharatiya Nyaya Sanhita, 2023) and IPC
          §§390-402 (Indian Penal Code, 1860), plus relevant High Court and
          Supreme Court judgments interpreting these provisions.
        </p>
        <p>
          The assistant deliberately refuses out-of-scope questions. This is
          a feature, not a bug — narrow scope improves accuracy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Currency of information</h2>
        <p>
          The corpus is a static snapshot. Indian statutes are amended, case
          law evolves, and this assistant does not auto-update. Always
          cross-check citations against the current authoritative source
          (indiacode.nic.in for statutes, indiankanoon.org or the relevant
          court's official site for judgments).
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">No warranty</h2>
        <p>
          This service is provided as-is. The author makes no warranty of
          fitness for any particular purpose. You assume all risk for any use
          of the information returned.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Privacy</h2>
        <p>
          Queries are logged for operational purposes (rate limiting, abuse
          detection, quality monitoring). Client IPs are SHA-256 hashed before
          storage. The full text of each query is retained in the query log
          for 30 days. No analytics trackers, no third-party advertising,
          no data sold to anyone.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Bot protection</h2>
        <p>
          Cloudflare Turnstile provides invisible bot protection. The widget
          loads from challenges.cloudflare.com and is governed by Cloudflare's
          own privacy policy.
        </p>
      </section>

      <p className="text-xs text-muted-foreground">
        Last updated when the site was deployed. This is a personal portfolio
        project, not a commercial service.
      </p>
    </div>
  );
}
