import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useDisclaimerStore } from "@/stores/useDisclaimerStore";

/**
 * First-visit modal that gates the app behind an "I understand" click.
 * Once accepted (persisted to localStorage), it never shows again
 * for this browser. The legal Terms link routes to /terms for the
 * full disclaimer text.
 *
 * Rendered at the App root so it overlays whatever the user is
 * viewing on first arrival.
 */
export function FirstVisitModal() {
  const isAccepted = useDisclaimerStore((s) => s.isAccepted);
  const accept = useDisclaimerStore((s) => s.accept);

  // Defer the open state slightly so SSR / hydration doesn't flicker
  // the modal. On a static SPA this is mostly cosmetic.
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    setIsMounted(true);
  }, []);

  if (!isMounted) return null;

  return (
    <Dialog open={!isAccepted}>
      <DialogContent
        // Block clicking outside / ESC from dismissing. The user MUST click "I understand".
        onPointerDownOutside={(e) => {
          e.preventDefault();
        }}
        onEscapeKeyDown={(e) => {
          e.preventDefault();
        }}
      >
        <DialogHeader>
          <DialogTitle>Not legal advice</DialogTitle>
          <DialogDescription>Please read before continuing.</DialogDescription>
        </DialogHeader>

        <div className="space-y-3 text-sm text-foreground/90">
          <p>
            This is a <strong>research aid</strong>, not a substitute for a lawyer. Answers are
            generated by an AI model from a curated set of Indian statutes and judgments — citations
            are included so you can verify them.
          </p>
          <p>
            <strong>Don't rely on this for actual legal decisions.</strong> Statutes are amended;
            case law evolves; this corpus is a snapshot. If you have a real legal question, talk to
            a qualified advocate.
          </p>
          <p className="text-xs text-muted-foreground">
            Full terms:{" "}
            <Link to="/terms" className="underline">
              /terms
            </Link>
          </p>
        </div>

        <DialogFooter>
          <Button onClick={accept} size="lg" className="w-full sm:w-auto">
            I understand — continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
